### ISSUE TITLE
Should display "Command not found" if asciidoctor is not installed

### ISSUE THREAD

**Issue by Mazwak** [toyboot4e/adbook#9]
If asciidoctor is not installed, the error message does not say so.

It just says "x errors while building the book:", without outputting the actual error.
Like "command not found"

**Comment by toyboot4e** [comment]
That is indeed a helpful error message!

I tried adding one. I will test on Windows this weekend.

**Comment by toyboot4e** [comment]
I confirm the fix works on Windows, too.
